name=E_Serial
version=1.0.0
author=Mahmoud Ewise
maintainer=Mahmoud Ewise
sentence=Serial communication library for Arduino-based GD3160 device control via SPI
paragraph=Provides serial message handling and protocol implementation for Arduino-based GD3160 device control via SPI
category=Communication
url=
architectures=*
